ALTER TABLE checkouts
ADD COLUMN IF NOT EXISTS enable_timer BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS timer_minutes INTEGER DEFAULT 15,
ADD COLUMN IF NOT EXISTS timer_text TEXT DEFAULT 'Oferta expira em',
ADD COLUMN IF NOT EXISTS timer_bg_color TEXT DEFAULT '#ef4444',
ADD COLUMN IF NOT EXISTS timer_text_color TEXT DEFAULT '#ffffff';
